Healthify/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('', include('groceries.urls')),
    path('shopping-cart/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('unauthorized/', views.unauthorized, name='unauthorized'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.shopping_cart, name='shopping_cart'),
    path('<int:order_item_id>/increase-quantity', views.increase_quantity, name='increase-order-item-quantity'),
    path('<int:order_item_id>/decrease-quantity', views.decrease_quantity, name='decrease-order-item-quantity'),
    path('<int:order_item_id>/remove', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('confirmation/', views.confirmation, name='confirmation'),
    path('order-items-count/', views.order_items_count, name='order_items_counts'),
]

accounts/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.


class User(AbstractUser):
    class Role(models.TextChoices):
        ADMINISTRATOR = 'ADMINISTRATOR', 'Administrator'
        CONSUMER = 'CONSUMER', 'Consumer'
        SELLER = 'SELLER', 'Seller'

    base_role = Role.ADMINISTRATOR

    role = models.CharField(max_length=255, choices=Role.choices)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.role = self.base_role

        return super().save(*args, **kwargs)


class ConsumerManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(role=User.Role.CONSUMER)


class Consumer(User):
    base_role = User.Role.CONSUMER
    objects = ConsumerManager()

    class Meta:
        proxy = True


class SellerManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(role=User.Role.SELLER)


class Seller(User):
    base_role = User.Role.SELLER
    objects = SellerManager()

    class Meta:
        proxy = True

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

from accounts.models import Consumer


class CustomConsumerCreationForm(UserCreationForm):
    class Meta:
        model = Consumer
        fields = ['username', 'first_name', 'last_name', 'password1', 'password2']

accounts/views.py
from django.contrib import auth, messages
from django.shortcuts import render, redirect

from accounts.decorators import unauthenticated
from accounts.forms import CustomConsumerCreationForm


# Create your views here.


@unauthenticated(redirect_url='/')
def register(request):
    errors = None
    if request.method == 'POST':
        form = CustomConsumerCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, error)

    context = {'errors': errors}
    return render(request, 'accounts/register.html', context)


@unauthenticated(redirect_url='/')
def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)

            redirect_url = request.GET.get('next')
            if redirect_url is not None:
                return redirect(redirect_url)

            return redirect('/')
        else:
            messages.error(request, 'Username or password is incorrect.')

    context = {}
    return render(request, 'accounts/login.html', context)


def logout(request):
    auth.logout(request)

    return redirect('accounts:login')


def unauthorized(request):
    return render(request, 'accounts/unauthorized.html')

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login{% endblock %}
{% block content %}
    <div class="container">
        <div class="row mt-5 justify-content-center">
            <div class="col-12 col-lg-6">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="row mb-3">
                        <div class="col">
                            {% if messages %}
                                <ul class="messages">
                                    {% for message in messages %}
                                        <li  {% if message.tags %}
                                            class="{{ message.tags }}" {% endif %}> {{ message }} </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col">
                            <div class="form-floating">
                                <input class="form-control form-control-sm rounded-5 px-5" type="text" name="username"
                                       maxlength="150" required="" id="id_username" placeholder="Username">
                                <label class="px-5" for="id_username">Username</label>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col">
                            <div class="form-floating">
                                <input class="form-control form-control-sm rounded-5 px-5" type="password"
                                       name="password" required=""
                                       id="id_password" placeholder="Password">
                                <label class="px-5" for="id_password">Password</label>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col">
                            <button type="submit" class="btn btn-primary text-white rounded-5 px-5"
                                    style="font-style: italic;">
                                Login
                            </button>
                            <a href="{% url 'accounts:register' %}"
                               type="button" class="btn btn-secondary text-primary rounded-5 px-5 ms-3"
                               style="font-style: italic;">
                                Register
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-12 col-lg-8">
                <img class="img-fluid w-100"
                     src="{% static 'images/man-supplying-ingredients-woman-making-drink.jpg' %}"
                     alt=""/>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Register{% endblock %}
{% block content %}
    <div class="container">
        <div class="row mt-5 justify-content-center">
            <div class="col-12 col-lg-6">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="row mb-3">
                        <div class="col">
                            {% if messages %}
                                <ul class="messages">
                                    {% for message in messages %}
                                        <li  {% if message.tags %}
                                            class="{{ message.tags }}" {% endif %}> {{ message }} </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-12 col-lg-6">
                            <div class="form-floating">
                                <input class="form-control form-control-sm rounded-5 px-5" type="text" name="first_name"
                                       maxlength="150"
                                       id="id_first_name" placeholder="First Name">
                                <label class="px-5" for="id_first_name">First Name</label>
                            </div>
                        </div>
                        <div class="col-12 col-lg-6 mt-3 mt-lg-0">
                            <div class="form-floating">
                                <input class="form-control form-control-sm rounded-5 px-5" type="text" name="last_name"
                                       maxlength="150" id="id_last_name" placeholder="Last Name">
                                <label class="px-5" for="id_last_name">Last Name</label>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col">
                            <div class="form-floating">
                                <input class="form-control form-control-sm rounded-5 px-5" type="text" name="username"
                                       maxlength="150" required="" id="id_username" placeholder="Username">
                                <label class="px-5" for="id_username">Username</label>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-12 col-lg-6">
                            <div class="form-floating">
                                <input class="form-control form-control-sm rounded-5 px-5" type="password"
                                       name="password1" autocomplete="new-password" required=""
                                       id="id_password1" placeholder="Password">
                                <label class="px-5" for="id_password1">Password</label>
                            </div>
                        </div>
                        <div class="col-12 col-lg-6 mt-3 mt-lg-0">
                            <div class="form-floating">
                                <input class="form-control form-control-sm rounded-5 px-5" type="password"
                                       name="password2"
                                       autocomplete="new-password" required=""
                                       id="id_password2" placeholder="Confirm Password">
                                <label class="px-5" for="id_password2">Confirm Password</label>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col">
                            <button type="submit" class="btn btn-primary text-white rounded-5 px-5"
                                    style="font-style: italic;">
                                Register
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-12 col-lg-8">
                <img class="img-fluid w-100"
                     src="{% static 'images/man-supplying-ingredients-woman-making-drink.jpg' %}"
                     alt=""/>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/unauthorized.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Access Denied</title>

    <link href="{% static 'assets/scss/custom.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
<div id="main-wrapper">
    <main class="d-flex">
        <div class="container flex-grow-1">
            <div class="row h-100 justify-content-center align-items-center">
                <div class="col-6 bg-info p-5 rounded-5 text-center">
                    You are authenticated as <span class="badge bg-primary text-white">{{ user.username }}</span>, but
                    are not authorized to access this page. Would you
                    like to login to a different account?
                    <a href="{% url 'accounts:logout' %}" class="btn btn-primary text-white rounded-5 px-5 mt-5">
                        Log in
                    </a>
                </div>
            </div>
        </div>
    </main>
</div>

<script src="{% static 'popper-2.11.8/popper.min.js' %}"></script>
<script src="{% static 'bootstrap-5.3.0/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>