Healthify/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('', include('groceries.urls')),
    path('shopping-cart/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groceries/urls.py
from django.urls import path
from . import views

app_name = 'groceries'

urlpatterns = [
    path('', views.home, name='home'),
    path('groceries/', views.groceries, name='groceries'),
    path('groceries/<int:grocery_id>', views.grocery_details, name='grocery_details'),
    path('groceries/add', views.add_grocery, name='add_grocery'),
    path('groceries/<int:grocery_id>/edit', views.edit_grocery, name='edit_grocery'),
    path('groceries/<int:grocery_id>/delete', views.delete_grocery, name='delete_grocery'),
    path('<int:grocery_id>/add-to-cart/', views.add_to_cart, name='add_to_cart'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.shopping_cart, name='shopping_cart'),
    path('<int:order_item_id>/increase-quantity', views.increase_quantity, name='increase-order-item-quantity'),
    path('<int:order_item_id>/decrease-quantity', views.decrease_quantity, name='decrease-order-item-quantity'),
    path('<int:order_item_id>/remove', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('confirmation/', views.confirmation, name='confirmation'),
    path('order-items-count/', views.order_items_count, name='order_items_counts'),
]

groceries/models.py
from django.db import models

from accounts.models import Seller


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Diet(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class NutritionFactsLabel(models.Model):
    fats = models.DecimalField(max_digits=6, decimal_places=2)
    saturated_fats = models.DecimalField(max_digits=6, decimal_places=2)
    polyunsaturated_fats = models.DecimalField(max_digits=6, decimal_places=2)
    monounsaturated_fats = models.DecimalField(max_digits=6, decimal_places=2)
    carbohydrates = models.DecimalField(max_digits=6, decimal_places=2)
    dietary_fiber = models.DecimalField(max_digits=6, decimal_places=2)
    sugars = models.DecimalField(max_digits=6, decimal_places=2)
    proteins = models.DecimalField(max_digits=6, decimal_places=2)
    calories = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return f'Nutrition facts (per 100 grams) for {self.grocery}'


class Grocery(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    categories = models.ManyToManyField(Category)
    diets = models.ManyToManyField(Diet)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    quantity = models.IntegerField()
    image = models.ImageField(upload_to='images/')
    nutrition_facts_label = models.OneToOneField(NutritionFactsLabel, on_delete=models.CASCADE)
    creator = models.ForeignKey(Seller, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'groceries'

    def __str__(self):
        return self.name

groceries/forms.py
from django import forms

from groceries.models import Grocery, NutritionFactsLabel


class GroceryForm(forms.ModelForm):
    class Meta:
        model = Grocery
        exclude = ('creator', 'nutrition_facts_label')


class NutritionFactsLabelForm(forms.ModelForm):
    class Meta:
        model = NutritionFactsLabel
        fields = '__all__'

groceries/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

from accounts.decorators import allowed_users
from accounts.models import User
from groceries.forms import NutritionFactsLabelForm, GroceryForm
from groceries.models import Category, Diet, Grocery
from orders.models import Order, OrderItem


# Create your views here.


def home(request):
    return render(request, 'groceries/home.html')


@login_required(login_url='accounts:login')
@allowed_users(roles=(User.Role.CONSUMER, User.Role.SELLER, User.Role.ADMINISTRATOR,))
def groceries(request):
    all_groceries = Grocery.objects.all().order_by('name')

    category = request.GET.get('category')
    if category is not None:
        all_groceries = all_groceries.filter(categories__name__in=[category]).all().order_by('name')
    diet = request.GET.get('diet')
    if diet is not None:
        all_groceries = all_groceries.filter(diets__name__in=[diet]).all().order_by('name')

    page = Paginator(all_groceries, 9)
    page_list = request.GET.get('page')
    page = page.get_page(page_list)

    context = {'categories': Category.objects.all(), 'diets': Diet.objects.all(), 'page': page}
    return render(request, 'groceries/groceries.html', context)


@login_required(login_url='accounts:login')
@allowed_users(roles=(User.Role.CONSUMER, User.Role.SELLER, User.Role.ADMINISTRATOR,))
def grocery_details(request, grocery_id):
    grocery = Grocery.objects.filter(id=grocery_id).first()

    context = {'grocery': grocery}
    return render(request, 'groceries/grocery-details.html', context)


@login_required(login_url='accounts:login')
@allowed_users(roles=(User.Role.SELLER,))
def add_grocery(request):
    nutrition_facts_label_form_errors = None
    grocery_form_errors = None
    if request.method == 'POST':
        nutrition_facts_label_form = NutritionFactsLabelForm(request.POST, request.FILES)
        grocery_form = GroceryForm(request.POST, request.FILES)
        if all((nutrition_facts_label_form.is_valid(), grocery_form.is_valid())):
            nutrition_facts_label = nutrition_facts_label_form.save()
            grocery = grocery_form.save(commit=False)
            grocery.creator = request.user
            grocery.nutrition_facts_label = nutrition_facts_label
            grocery.save()
            grocery.categories.set(grocery_form.cleaned_data['categories'])
            grocery.diets.set(grocery_form.cleaned_data['diets'])
            grocery.save()

            return redirect('groceries:groceries')
        else:
            nutrition_facts_label_form_errors = nutrition_facts_label_form.errors
            grocery_form_errors = grocery_form.errors

    context = {'categories': Category.objects.all(), 'diets': Diet.objects.all(),
               'nutrition_facts_label_form_errors': nutrition_facts_label_form_errors,
               'grocery_form_errors': grocery_form_errors}
    return render(request, 'groceries/add-grocery.html', context)


@login_required(login_url='accounts:login')
@allowed_users(roles=(User.Role.SELLER,))
def edit_grocery(request, grocery_id):
    grocery = Grocery.objects.get(id=grocery_id)
    nutrition_facts_label_form_errors = None
    grocery_form_errors = None
    if request.method == 'POST':
        nutrition_facts_label_form = NutritionFactsLabelForm(request.POST, request.FILES)
        grocery_form = GroceryForm(request.POST, request.FILES)
        if all((nutrition_facts_label_form.is_valid(), grocery_form.is_valid())):
            grocery.nutrition_facts_label.fats = nutrition_facts_label_form.cleaned_data['fats']
            grocery.nutrition_facts_label.saturated_fats = nutrition_facts_label_form.cleaned_data['saturated_fats']
            grocery.nutrition_facts_label.polyunsaturated_fats = nutrition_facts_label_form.cleaned_data[
                'polyunsaturated_fats']
            grocery.nutrition_facts_label.monounsaturated_fats = nutrition_facts_label_form.cleaned_data[
                'monounsaturated_fats']
            grocery.nutrition_facts_label.carbohydrates = nutrition_facts_label_form.cleaned_data['carbohydrates']
            grocery.nutrition_facts_label.dietary_fiber = nutrition_facts_label_form.cleaned_data['dietary_fiber']
            grocery.nutrition_facts_label.sugars = nutrition_facts_label_form.cleaned_data['sugars']
            grocery.nutrition_facts_label.proteins = nutrition_facts_label_form.cleaned_data['proteins']
            grocery.nutrition_facts_label.calories = nutrition_facts_label_form.cleaned_data['calories']
            grocery.nutrition_facts_label.save()

            grocery.name = grocery_form.cleaned_data['name']
            grocery.description = grocery_form.cleaned_data['description']
            grocery.categories.set(grocery_form.cleaned_data['categories'])
            grocery.diets.set(grocery_form.cleaned_data['diets'])
            grocery.price = grocery_form.cleaned_data['price']
            grocery.quantity = grocery_form.cleaned_data['quantity']
            grocery.image = grocery_form.cleaned_data['image']
            grocery.save()

            return redirect('groceries:grocery_details', grocery_id)
        else:
            nutrition_facts_label_form_errors = nutrition_facts_label_form.errors
            grocery_form_errors = grocery_form.errors

    context = {'categories': Category.objects.all(), 'diets': Diet.objects.all(),
               'nutrition_facts_label_form_errors': nutrition_facts_label_form_errors,
               'grocery_form_errors': grocery_form_errors, 'grocery': grocery}
    return render(request, 'groceries/edit-grocery.html', context)


@login_required(login_url='accounts:login')
@allowed_users(roles=(User.Role.SELLER,))
def delete_grocery(request, grocery_id):
    if request.method == 'POST':
        grocery = Grocery.objects.get(id=grocery_id)
        grocery.nutrition_facts_label.delete()
        grocery.delete()

    return redirect('groceries:groceries')


@login_required(login_url='accounts:login')
@allowed_users(roles=(User.Role.CONSUMER,))
def add_to_cart(request, grocery_id):
    grocery = Grocery.objects.filter(id=grocery_id).first()
    consumer = request.user
    order, created = Order.objects.get_or_create(consumer=consumer, complete=False)
    if order is None:
        order = created
    order_item = order.orderitem_set.filter(grocery=grocery).first()
    if order_item:
        order_item.quantity += 1
    else:
        order_item = OrderItem()
        order_item.grocery = grocery
        order_item.order = order
    order_item.save()

    return redirect('orders:shopping_cart')

templates/groceries/add-grocery.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Add new grocery{% endblock %}
{% block content %}
    <div class="container">
        <form method="POST" action="{% url 'groceries:add_grocery' %}" id="add-grocery" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="container">
                <div class="row">
                    <div class="col-6 px-5">
                        <div class="form-floating mb-3">
                            <input class="form-control rounded-5 px-5" type="text" name="name" maxlength="255"
                                   required=""
                                   id="id_name"
                                   placeholder="Name">
                            <label for="id_name" class="px-5">Name</label>
                        </div>
                        <div class="form-floating mb-3">
                    <textarea class="form-control rounded-5 px-5" name="description" cols="40" rows="10" required=""
                              id="id_description"
                              placeholder="Description" style="height: 100px;"></textarea>
                            <label for="id_description" class="px-5">Description</label>
                        </div>
                        <div class="form-floating mb-3">
                            <select class="form-select h-25 rounded-5 px-5" name="categories" required="" id="id_categories" multiple>
                                {% for category in categories %}
                                    <option value="{{ category.id }}">{{ category.name }}</option>
                                {% endfor %}
                            </select>
                            <label for="id_categories" class="px-5">Categories</label>
                        </div>
                        <div class="form-floating mb-3">
                            <select class="form-select h-25 rounded-5 px-5" name="diets" required="" id="id_diets" multiple>
                                {% for diet in diets %}
                                    <option value="{{ diet.id }}">{{ diet.name }}</option>
                                {% endfor %}
                            </select>
                            <label for="id_diets" class="px-5">Diets</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input class="form-control rounded-5 px-5" type="number" name="price" step="0.01"
                                   required=""
                                   id="id_price" placeholder="Price">
                            <label for="id_price" class="px-5">Price</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input class="form-control rounded-5 px-5" type="number" name="quantity" required=""
                                   id="id_quantity" placeholder="Quantity">
                            <label for="id_quantity" class="px-5">Quantity</label>
                        </div>
                        <div class="mb-3" style="position: relative;">
                            <label for="id_image"
                                   class="form-control rounded-5 px-5 py-3 d-flex justify-content-between"
                                   style="cursor: pointer;">
                        <span id="image-label" class="px-5"
                              style="color: rgba(var(--bs-body-color-rgb), 0.65); transform: scale(0.85) translateY(-0.5rem) translateX(0.15rem); position: absolute;">Image</span>
                                <input class="pt-3" type="file" name="image" accept="image/*" required="" id="id_image"
                                       style="cursor: pointer;">
                                <span class="pt-3 pb-0"><i class="bi bi-upload"></i></span>
                            </label>
                        </div>
                        <div>
                            {% if grocery_form_errors %}
                                {{ grocery_form_errors }}
                            {% endif %}
                            {% if nutrition_facts_label_form_errors %}
                                {{ nutrition_facts_label_form_errors }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-6 px-5">
                        <div class="rounded-5 py-3 px-5 nutrition-facts-label text-white"
                             style="background-color: rgba(83, 124, 229, 255); height: fit-content;">
                            <h3 class="pt-3">Nutrition facts (per 100 grams)</h3>
                            <hr class="border-5 border-white w-100 opacity-100 rounded-5 pb-0"/>
                            <div class="mb-2 d-flex align-items-center main-label">
                                <label class="form-label mb-0 me-3" for="id_fats"><strong>Fats</strong></label>
                                <input class="form-control form-control-sm rounded-5 text-center" type="number"
                                       name="fats"
                                       step="0.01" required="" id="id_fats">
                                <div class="ms-3">grams</div>
                            </div>
                            <div class="mb-2 d-flex align-items-center">
                                <label class="form-label mb-0 me-3" for="id_saturated_fats">Saturated fats</label>
                                <input class="form-control form-control-sm rounded-5 text-center" type="number"
                                       name="saturated_fats" step="0.01" required="" id="id_saturated_fats">
                                <div class="ms-3">grams</div>
                            </div>
                            <div class="mb-2 d-flex align-items-center">
                                <label class="form- mb-0 me-3" for="id_polyunsaturated_fats">Polyunsaturated
                                    fats</label>
                                <input class="form-control form-control-sm rounded-5 text-center" type="number"
                                       name="polyunsaturated_fats" step="0.01" required=""
                                       id="id_polyunsaturated_fats">
                                <div class="ms-3">grams</div>
                            </div>
                            <div class="mb-2 d-flex align-items-center">
                                <label class="form-label mb-0 me-3" for="id_monounsaturated_fats">Monounsaturated
                                    fats</label>
                                <input class="form-control form-control-sm rounded-5 text-center" type="number"
                                       name="monounsaturated_fats" step="0.01" required=""
                                       id="id_monounsaturated_fats">
                                <div class="ms-3">grams</div>
                            </div>
                            <div class="mb-2 d-flex align-items-center main-label">
                                <label class="form-label mb-0 me-3"
                                       for="id_carbohydrates"><strong>Carbohydrates</strong></label>
                                <input class="form-control form-control-sm rounded-5 text-center" type="number"
                                       name="carbohydrates"
                                       step="0.01" required="" id="id_carbohydrates">
                                <div class="ms-3">grams</div>
                            </div>
                            <div class="mb-2 d-flex align-items-center">
                                <label class="form-label mb-0 me-3" for="id_dietary_fiber">Dietary fiber</label>
                                <input class="form-control form-control-sm rounded-5 text-center" type="number"
                                       name="dietary_fiber"
                                       step="0.01" required="" id="id_dietary_fiber">
                                <div class="ms-3">grams</div>
                            </div>
                            <div class="mb-2 d-flex align-items-center">
                                <label class="form-label mb-0 me-3" for="id_sugars">Sugars</label>
                                <input class="form-control form-control-sm rounded-5 text-center" type="number"
                                       name="sugars"
                                       step="0.01" required="" id="id_sugars">
                                <div class="ms-3">grams</div>
                            </div>
                            <div class="mb-2 d-flex align-items-center main-label">
                                <label class="form-label mb-0 me-3" for="id_proteins"><strong>Proteins</strong></label>
                                <input class="form-control form-control-sm rounded-5 text-center" type="number"
                                       name="proteins"
                                       step="0.01" required="" id="id_proteins">
                                <div class="ms-3">grams</div>
                            </div>
                            <div class="mb-2 d-flex align-items-center">
                                <label class="form-label mb-0 me-3" for="id_calories"><strong
                                        style="font-size: 24px;">Calories</strong></label>
                                <input class="form-control form-control-sm rounded-5 text-center" type="number"
                                       name="calories"
                                       step="0.01" required="" id="id_calories">
                                <div class="ms-3" style="font-size: 32px;">kcal</div>
                            </div>
                        </div>
                        <div class="d-flex justify-content-end my-4">
                            <button type="submit" class="btn btn-primary text-white rounded-5 w-100" form="add-grocery">
                                <strong>Submit</strong>
                            </button>
                        </div>
                        <div>
                            <img class="img-fluid"
                                 src="{% static 'images/young-women-presenting-healthy-foods.jpg' %}"/>
                        </div>
                    </div>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

templates/groceries/grocery-details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Grocery Details{% endblock %}
{% block content %}
    <div class="container">
        <div class="row mb-3">
            <div class="col-5 bg-info rounded-5 px-5 py-3 d-flex justify-content-center align-items-center">
                <img src="{{ MEDIA_URL }}{{ grocery.image.url }}" class="img-fluid w-75" alt=""/>
            </div>
            <div class="col-7 px-5 py-3 d-flex flex-column justify-content-between">
                <h1>{{ grocery.name }}</h1>
                <p style="text-align: justify;">{{ grocery.description }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-5 rounded-5 px-5 py-3 nutrition-facts-label text-white"
                 style="background-color: rgba(83, 124, 229, 255); height: fit-content;">
                <h3 class="pt-3">Nutrition facts (per 100 grams)</h3>
                <hr class="border-5 border-white w-100 opacity-100 rounded-5 pb-0"/>
                <div class="d-flex align-items-center main-label">
                    <label class="form-label mb-0 me-3" for="id_fats"><strong>Fats:</strong></label>
                    <div class="ms-1">{{ grocery.nutrition_facts_label.fats }} grams</div>
                </div>
                <div class="ms-3">
                    <div class="d-flex align-items-center">
                        <label class="form-label mb-0 me-3" for="id_saturated_fats">Saturated fats:</label>
                        <div class="ms-1">{{ grocery.nutrition_facts_label.saturated_fats }} grams</div>
                    </div>
                    <div class="d-flex align-items-center">
                        <label class="form- mb-0 me-3" for="id_polyunsaturated_fats">Polyunsaturated fats:</label>
                        <div class="ms-1">{{ grocery.nutrition_facts_label.polyunsaturated_fats }} grams</div>
                    </div>
                    <div class="d-flex align-items-center">
                        <label class="form-label mb-0 me-3" for="id_monounsaturated_fats">Monounsaturated
                            fats:</label>
                        <div class="ms-1">{{ grocery.nutrition_facts_label.monounsaturated_fats }} grams</div>
                    </div>
                </div>
                <div class="d-flex align-items-center main-label">
                    <label class="form-label mb-0 me-3"
                           for="id_carbohydrates"><strong>Carbohydrates:</strong></label>
                    <div class="ms-1">{{ grocery.nutrition_facts_label.carbohydrates }} grams</div>
                </div>
                <div class="ms-3">
                    <div class="d-flex align-items-center">
                        <label class="form-label mb-0 me-3" for="id_dietary_fiber">Dietary fiber:</label>
                        <div class="ms-1">{{ grocery.nutrition_facts_label.dietary_fiber }} grams</div>
                    </div>
                    <div class="d-flex align-items-center">
                        <label class="form-label mb-0 me-3" for="id_sugars">Sugars:</label>
                        <div class="ms-1">{{ grocery.nutrition_facts_label.sugars }} grams</div>
                    </div>
                </div>
                <div class="d-flex align-items-center main-label">
                    <label class="form-label mb-0 me-3" for="id_proteins"><strong>Proteins:</strong></label>
                    <div class="ms-1">{{ grocery.nutrition_facts_label.proteins }} grams</div>
                </div>
                <div class="d-flex align-items-center">
                    <label class="form-label mb-0 me-3" for="id_calories"><strong
                            style="font-size: 24px;">Calories:</strong></label>
                    <div class="ms-1" style="font-size: 32px;">{{ grocery.nutrition_facts_label.calories }} kcal</div>
                </div>
            </div>
            <div class="col-7 px-5 py-3">
                <div class="row mb-3">
                    <div class="col d-flex justify-content-start flex-wrap">
                        {% for category in grocery.categories.all %}
                            <div class="bg-success rounded-5 px-5 py-1 mb-3 me-3">
                                <strong style="color: rgba(83, 124, 229, 255);">{{ category }}</strong>
                            </div>
                        {% endfor %}
                        {% for diet in grocery.diets.all %}
                            <div class="bg-success rounded-5 px-5 py-1 mb-3 me-3">
                                <strong style="color: rgba(83, 124, 229, 255);">{{ diet }}</strong>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col d-flex">
                        <div class="rounded-5 px-5 py-2 w-50 text-center"
                             style="background-color: rgba(43, 70, 139, 255);">
                            <strong style="font-size: 28px;" class="text-white">${{ grocery.price }}</strong>
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col d-flex justify-content-end">
                        {% if user.role == 'CONSUMER' %}
                            <a href="{% url 'groceries:add_to_cart' grocery.id %}"
                                    class="btn btn-primary text-white rounded-5 px-5 ms-3"
                                    style="font-style: italic">
                                Add to Cart
                            </a>
                        {% endif %}
                        {% if user.role == 'SELLER' %}
                            <a href="{% url 'groceries:edit_grocery' grocery.id %}"
                               class="btn btn-warning text-white rounded-5 px-5 ms-3"
                               style="font-style: italic">Edit</a>
                            <form method="POST" action="{% url 'groceries:delete_grocery' grocery.id %}">
                                {% csrf_token %}
                                <button type="submit"
                                        class="btn btn-danger text-white rounded-5 px-5 ms-3"
                                        style="font-style: italic">Delete
                                </button>
                            </form>
                        {% endif %}
                        <a href="{% url 'groceries:groceries' %}"
                           class="btn btn-secondary text-primary rounded-5 px-5 ms-3"
                           style="font-style: italic">Back to Products</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}