Healthify/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('', include('groceries.urls')),
    path('shopping-cart/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('unauthorized/', views.unauthorized, name='unauthorized'),
]

groceries/urls.py
from django.urls import path
from . import views

app_name = 'groceries'

urlpatterns = [
    path('', views.home, name='home'),
    path('groceries/', views.groceries, name='groceries'),
    path('groceries/<int:grocery_id>', views.grocery_details, name='grocery_details'),
    path('groceries/add', views.add_grocery, name='add_grocery'),
    path('groceries/<int:grocery_id>/edit', views.edit_grocery, name='edit_grocery'),
    path('groceries/<int:grocery_id>/delete', views.delete_grocery, name='delete_grocery'),
    path('<int:grocery_id>/add-to-cart/', views.add_to_cart, name='add_to_cart'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.shopping_cart, name='shopping_cart'),
    path('<int:order_item_id>/increase-quantity', views.increase_quantity, name='increase-order-item-quantity'),
    path('<int:order_item_id>/decrease-quantity', views.decrease_quantity, name='decrease-order-item-quantity'),
    path('<int:order_item_id>/remove', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('confirmation/', views.confirmation, name='confirmation'),
    path('order-items-count/', views.order_items_count, name='order_items_counts'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>

    <link href="{% static 'assets/scss/custom.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
<div id="main-wrapper">
    <header>
        <div class="container">
            <nav class="header navbar navbar-expand-lg bg-body-tertiary px-5 my-3 rounded-5">
                <a class="navbar-brand" href="{% url 'groceries:home' %}">Healthify</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav d-flex align-items-center ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'groceries:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'groceries:groceries' %}">Groceries</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li>
                                <div class="bg-secondary text-primary rounded-5 px-3 py-2 mx-1">
                                    {{ user.username }}
                                </div>
                            </li>
                            <li>
                                {% if user.role == 'CONSUMER' %}
                                    <a class="nav-link me-0" href="{% url 'orders:shopping_cart' %}"
                                       style="position: relative;">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                             fill="currentColor" class="bi bi-cart-fill" viewBox="0 0 16 16">
                                            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"></path>
                                        </svg>
                                        <span class="order-items-count">0</span>
                                    </a>
                                {% endif %}
                            </li>
                            <li>
                                <a href="{% url 'accounts:logout' %}"
                                   class="btn btn-primary text-white rounded-5 px-3 ms-5">
                                    Logout
                                </a>
                            </li>
                        {% else %}
                            <li>
                                <a href="{% url 'accounts:login' %}"
                                   class="btn btn-primary text-white rounded-5 px-3 ms-5">
                                    Login
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <div class="container">
            <div class="footer px-5 my-3 rounded-5 d-flex justify-content-between">
                <p class="message py-3 mb-0">A recipe has no soul. You, as the cook, must bring soul to the recipe.</p>
                <p class="icons py-3 mb-0">
                    <i class="bi bi-facebook"></i>
                    <i class="bi bi-instagram"></i>
                    <i class="bi bi-twitter"></i>
                    <i class="bi bi-youtube"></i>
                </p>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'jquery-3.7.0/code.jquery.com_jquery-3.7.0.min.js' %}"></script>
<script src="{% static 'popper-2.11.8/popper.min.js' %}"></script>
<script src="{% static 'bootstrap-5.3.0/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>