Healthify/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('', include('groceries.urls')),
    path('shopping-cart/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groceries/urls.py
from django.urls import path
from . import views

app_name = 'groceries'

urlpatterns = [
    path('', views.home, name='home'),
    path('groceries/', views.groceries, name='groceries'),
    path('groceries/<int:grocery_id>', views.grocery_details, name='grocery_details'),
    path('groceries/add', views.add_grocery, name='add_grocery'),
    path('groceries/<int:grocery_id>/edit', views.edit_grocery, name='edit_grocery'),
    path('groceries/<int:grocery_id>/delete', views.delete_grocery, name='delete_grocery'),
    path('<int:grocery_id>/add-to-cart/', views.add_to_cart, name='add_to_cart'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.shopping_cart, name='shopping_cart'),
    path('<int:order_item_id>/increase-quantity', views.increase_quantity, name='increase-order-item-quantity'),
    path('<int:order_item_id>/decrease-quantity', views.decrease_quantity, name='decrease-order-item-quantity'),
    path('<int:order_item_id>/remove', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('confirmation/', views.confirmation, name='confirmation'),
    path('order-items-count/', views.order_items_count, name='order_items_counts'),
]

orders/models.py
from django.db import models

from accounts.models import Consumer
from groceries.models import Grocery


# Create your models here.


class Order(models.Model):
    consumer = models.ForeignKey(Consumer, on_delete=models.CASCADE)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)

    @property
    def total(self):
        total_price = 0
        for order_item in self.orderitem_set.all():
            total_price += order_item.subtotal

        return total_price

    def __str__(self):
        return f'Order No. {self.id} ({self.consumer})'


class OrderItem(models.Model):
    grocery = models.ForeignKey(Grocery, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def subtotal(self):
        return self.grocery.price * self.quantity

    def __str__(self):
        return f'Grocery: {self.grocery}, Quantity: {self.quantity}'


class ShippingInformation(models.Model):
    full_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.full_name} - {self.address}, {self.city}'


class PaymentDetails(models.Model):
    online_payment = models.BooleanField(default=False)
    card_holder = models.CharField(max_length=255, blank=True)
    card_number = models.CharField(max_length=255, blank=True)
    card_code = models.CharField(max_length=255, blank=True)
    expiry_date = models.CharField(max_length=255, blank=True)

    class Meta:
        verbose_name_plural = 'Payment details'


class Checkout(models.Model):
    consumer = models.ForeignKey(Consumer, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    shipping_information = models.ForeignKey(ShippingInformation, on_delete=models.CASCADE)
    payment_details = models.ForeignKey(PaymentDetails, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.consumer} - {self.order}'

orders/forms.py
from django import forms

from orders.models import ShippingInformation, PaymentDetails


class ShippingInformationForm(forms.ModelForm):
    class Meta:
        model = ShippingInformation
        fields = '__all__'


class PaymentDetailsForm(forms.ModelForm):
    class Meta:
        model = PaymentDetails
        fields = '__all__'

orders/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect

from accounts.decorators import allowed_users
from accounts.models import User
from orders.forms import ShippingInformationForm, PaymentDetailsForm
from orders.models import Order, Checkout


# Create your views here.


@login_required(login_url='accounts:login')
@allowed_users(roles=(User.Role.CONSUMER,))
def shopping_cart(request):
    consumer = request.user
    order, created = Order.objects.get_or_create(consumer=consumer, complete=False)
    if order is None:
        order = created
    items = order.orderitem_set.all()

    context = {'items': items, 'total_price': order.total}
    return render(request, 'orders/shopping-cart.html', context)


@login_required(login_url='accounts:login')
@allowed_users(roles=(User.Role.CONSUMER,))
def increase_quantity(request, order_item_id):
    consumer = request.user
    order, created = Order.objects.get_or_create(consumer=consumer, complete=False)
    if order is None:
        order = created
    order_item = order.orderitem_set.filter(id=order_item_id).first()
    if order_item:
        order_item.quantity += 1
        order_item.save()

    return redirect('orders:shopping_cart')


@login_required(login_url='accounts:login')
@allowed_users(roles=(User.Role.CONSUMER,))
def decrease_quantity(request, order_item_id):
    consumer = request.user
    order, created = Order.objects.get_or_create(consumer=consumer, complete=False)
    if order is None:
        order = created
    order_item = order.orderitem_set.filter(id=order_item_id).first()
    if order_item and order_item.quantity > 1:
        order_item.quantity -= 1
        order_item.save()

    return redirect('orders:shopping_cart')


@login_required(login_url='accounts:login')
@allowed_users(roles=(User.Role.CONSUMER,))
def remove_from_cart(request, order_item_id):
    if request.method == 'POST':
        consumer = request.user
        order, created = Order.objects.get_or_create(consumer=consumer, complete=False)
        if order is None:
            order = created
        order_item = order.orderitem_set.filter(id=order_item_id).first()
        if order_item:
            order_item.delete()

    return redirect('orders:shopping_cart')


@login_required(login_url='accounts:login')
@allowed_users(roles=(User.Role.CONSUMER,))
def checkout(request):
    shipping_information_form_errors = None
    payment_details_form_errors = None
    if request.method == 'POST':
        shipping_information_form = ShippingInformationForm(request.POST)
        payment_details_form = PaymentDetailsForm(request.POST)
        if all((shipping_information_form.is_valid(), payment_details_form.is_valid())):
            consumer = request.user
            order, created = Order.objects.get_or_create(consumer=consumer, complete=False)
            if order is None:
                order = created
            order.complete = True
            order.save()
            checkout_obj = Checkout()
            checkout_obj.consumer = consumer
            checkout_obj.order = order
            checkout_obj.shipping_information = shipping_information_form.save()
            checkout_obj.payment_details = payment_details_form.save()
            checkout_obj.save()

            return redirect('orders:confirmation')
        else:
            shipping_information_form_errors = shipping_information_form.errors
            payment_details_form_errors = payment_details_form.errors

    context = {'shipping_information_form_errors': shipping_information_form_errors,
               'payment_details_form_errors': payment_details_form_errors}
    return render(request, 'orders/checkout.html', context)


@login_required(login_url='accounts:login')
@allowed_users(roles=(User.Role.CONSUMER,))
def confirmation(request):
    return render(request, 'orders/confirmation.html')


@login_required(login_url='accounts:login')
@allowed_users(roles=(User.Role.CONSUMER,))
def order_items_count(request):
    consumer = request.user
    order, created = Order.objects.get_or_create(consumer=consumer, complete=False)
    if order is None:
        order = created

    return JsonResponse({'count': len(order.orderitem_set.all())})

templates/orders/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Checkout{% endblock %}
{% block content %}
    <div class="container checkout-form">
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-4">
                    <div class="container h-100 d-flex flex-column">
                        <div class="row">
                            <div class="col">
                                <h5 class="text-primary" style="font-style: italic;">Shipping Information</h5>
                            </div>
                        </div>
                        <div class="row flex-grow-1">
                            <div class="col px-3 py-3 rounded-5 d-flex align-items-end"
                                 style="background-color: rgba(83, 124, 229, 255);">
                                <div class="container">
                                    <div class="row">
                                        <div class="col">
                                            <input class="form-control px-4 my-3 rounded-5" type="text" name="full_name"
                                                   maxlength="255" required="" id="id_full_name"
                                                   placeholder="Full Name">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-8">
                                            <input class="form-control px-4 mb-3 rounded-5" type="text" name="address"
                                                   maxlength="255" required="" id="id_address"
                                                   placeholder="Address">
                                        </div>
                                        <div class="col-4">
                                            <input class="form-control px-4 mb-3 rounded-5" type="text"
                                                   placeholder="City" name="city" maxlength="255" required=""
                                                   id="id_city">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <input class="form-control px-4 mb-3 rounded-5" type="text"
                                                   placeholder="Phone Number" name="phone_number" maxlength="255"
                                                   required="" id="id_phone_number">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <div>
                                                {% if shipping_information_form_errors %}
                                                    {{ shipping_information_form_errors }}
                                                {% endif %}
                                                {% if payment_details_form_errors %}
                                                    {{ payment_details_form_errors }}
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-8">
                    <div class="container">
                        <div class="row">
                            <div class="col">
                                <h5 class="text-primary" style="font-style: italic;">Payment Details</h5>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col px-3 py-3 rounded-5" style="background-color: rgba(83, 124, 229, 255);">
                                <div class="container">
                                    <div class="row">
                                        <div class="col-6">
                                            <div class="container">
                                                <div class="row">
                                                    <div class="col">
                                                        <div class="form-check ps-0 mt-3">
                                                            <label class="form-check-label bg-white px-5 rounded-5 w-100"
                                                                   for="credit-card-payment">
                                                                <input
                                                                        class="form-check-input" type="radio" checked
                                                                        id="credit-card-payment" name="online_payment"
                                                                        value="True">
                                                                Credit Card Payment
                                                            </label>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col">
                                                        <input class="form-control px-4 my-3 rounded-5 credit-card-details"
                                                               type="text"
                                                               name="card_holder" maxlength="255" required=""
                                                               id="id_card_holder"
                                                               placeholder="Card Holder's Full Name">
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col">
                                                        <input class="form-control px-4 mb-3 rounded-5 credit-card-details"
                                                               type="text"
                                                               name="card_number" maxlength="255" required=""
                                                               id="id_card_number"
                                                               placeholder="Card Number">
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-4">
                                                        <input class="form-control px-4 mb-3 rounded-5 credit-card-details"
                                                               type="text"
                                                               name="card_code" maxlength="255" required=""
                                                               id="id_card_code"
                                                               placeholder="CVC">
                                                    </div>
                                                    <div class="col-8">
                                                        <input class="form-control px-4 mb-3 rounded-5 credit-card-details"
                                                               type="text"
                                                               name="expiry_date" maxlength="255" required=""
                                                               id="id_expiry_date"
                                                               placeholder="MM/YY">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-6">
                                            <div class="container">
                                                <div class="row">
                                                    <div class="col">
                                                        <div class="form-check ps-0 mt-3">
                                                            <label class="form-check-label bg-white px-5 rounded-5 w-100"
                                                                   for="payment-on-delivery">
                                                                <input class="form-check-input" type="radio"
                                                                       id="payment-on-delivery" name="online_payment"
                                                                       value="False">
                                                                Payment on Delivery
                                                            </label>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-4"></div>
                <div class="col-8">
                    <button type="submit" class="btn btn-primary px-5 rounded-5 mx-1">Confirm</button>
                    <a href="{% url 'orders:shopping_cart' %}"
                       class="btn btn-secondary px-5 rounded-5 text-primary mx-1">Cancel</a>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/orders/confirmation.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Confirmation{% endblock %}
{% block content %}
    <div class="container">
        <div class="container">
            <div class="row mb-3 px-5 py-3">
                <div class="col d-flex justify-content-center">
                    <div class="text-primary rounded-5 px-5 py-3 w-75 text-center"
                         style="font-size: 32px; font-weight: bold;">
                        Your order is currently being processed. <br/>
                        Thank you for your purchase.
                    </div>
                </div>
            </div>
        </div>
        <div class="container d-flex flex-column justify-content-between">
            <div class="row my-3">
                <div class="col-12 text-center">
                    <a href="{% url 'groceries:groceries' %}" class="btn btn-secondary text-primary rounded-5 px-5">
                        Back To Shopping
                    </a>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-6">
                    <img class="img-fluid"
                         src="{% static 'images/happy-young-couple-celebrating-good-news-flat-illustration.jpg' %}"/>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/orders/shopping-cart.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Shopping Cart{% endblock %}
{% block content %}
    <div class="container">
        {% if items %}
            <div class="container rounded-5" style="background-color: rgba(234, 243, 250, 255);">
                <div class="row p-3">
                    <div class="col">
                        <table class="text-center w-100 table-responsive">
                            <thead>
                            <tr>
                                <th class="px-3"></th>
                                <th class="px-3"><span class="rounded-5 px-3 py-2 my-1">Product</span></th>
                                <th class="px-3"><span class="rounded-5 px-3 py-2 my-1">Price</span></th>
                                <th class="px-3"><span class="rounded-5 px-3 py-2 my-1">Quantity</span></th>
                                <th class="px-3"><span class="rounded-5 px-3 py-2 my-1">Subtotal</span></th>
                                <th class="px-3"></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in items %}
                                <tr>
                                    <td class="px-3">
                                        <img src="{{ MEDIA_URL }}{{ item.grocery.image.url }}"
                                             class="img-fluid"
                                             style="max-width: 75px;"
                                        />
                                    </td>
                                    <td class="px-3"><span
                                            class="rounded-5 px-3 py-2 my-1">{{ item.grocery.name }}</span>
                                    </td>
                                    <td class="px-3"><span class="rounded-5 px-3 py-2 my-1">$2.49</span></td>
                                    <td class="px-3">
                            <span class="rounded-5 px-3 py-2 my-1 d-flex">
                                <span style="display: block;"
                                      class="text-center ms-auto ps-3">{{ item.quantity }}</span>
                                <span style="display: block;" class="ms-auto">
                                    <a href="{% url 'orders:increase-order-item-quantity' item.id %}"
                                       class="text-white"><i
                                            class="bi bi-arrow-up"></i></a>
                                    <a href="{% url 'orders:decrease-order-item-quantity' item.id %}"
                                       class="text-white"><i
                                            class="bi bi-arrow-down"></i></a>
                                </span>
                            </span>
                                    </td>
                                    <td class="px-3"><span class="rounded-5 px-3 py-2 my-1">${{ item.subtotal }}</span>
                                    </td>
                                    <td class="px-3">
                                        <form method="POST" action="{% url 'orders:remove_from_cart' item.id %}">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-danger rounded-5 px-3 py-2 my-1">Remove
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                            <tfoot>
                            <tr>
                                <td class="py-3"></td>
                                <td class="py-3"></td>
                                <td class="py-3"></td>
                                <td class="py-3"></td>
                                <td class="py-3"></td>
                                <td class="py-3"></td>
                            </tr>
                            <tr>
                                <td class="px-3"></td>
                                <td class="px-3"></td>
                                <td class="px-3"></td>
                                <th class="px-3"><span class="rounded-5 px-5 py-2 my-1">Total</span></th>
                                <td class="px-3"><span class="rounded-5 px-5 py-2 my-1">${{ total_price }}</span></td>
                                <td class="px-3"></td>
                            </tr>
                            <tr>
                                <td class="px-3"></td>
                                <td class="px-3"></td>
                                <td class="px-3"></td>
                                <td colspan="2" class="px-3">
                                    <a href="{% url 'orders:checkout' %}"
                                       class="btn btn-success rounded-5 px-5 py-2 my-1 w-100 text-primary">
                                        <strong style="font-size: 18px;">
                                            Proceed To Checkout
                                        </strong>
                                    </a>
                                </td>
                                <td class="px-3"></td>
                                <td class="px-3"></td>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-4"></div>
                    <div class="col-8">
                        <img class="img-fluid"
                             src="{% static 'images/man-supplying-ingredients-woman-making-drink.jpg' %}"/>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="container rounded-5" style="background-color: rgba(234, 243, 250, 255);">
                <div class="row mb-3 px-5 py-3">
                    <div class="col d-flex justify-content-center">
                        <div class="bg-primary text-white rounded-5 px-5 py-3 w-75 text-center"
                             style="font-size: 32px; font-style: italic; font-weight: bold;">
                            Looks like your shopping cart is empty.
                        </div>
                    </div>
                </div>
            </div>
            <div class="container d-flex flex-column justify-content-between">
                <div class="row my-3">
                    <div class="col-12 text-center">
                        <a href="{% url 'groceries:groceries' %}" class="btn btn-secondary text-primary rounded-5 px-5">
                            Back To Shopping
                        </a>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-8">
                        <img class="img-fluid"
                             src="{% static 'images/man-supplying-ingredients-woman-making-drink.jpg' %}"/>
                    </div>
                </div>
            </div>
        {% endif %}

    </div>
{% endblock %}